### ISSUE TITLE
Error in sanity check

### ISSUE THREAD

**Issue by nicolas-abril** [gmsoft-tuxicoman/bt-audio#3]
When running the script, I get the following error
```
Traceback (most recent call last):
  File "/run/media/nicolas/Coisas/Software/bt-audio/./bt-audio.py", line 416, in <module>
    main()
  File "/run/media/nicolas/Coisas/Software/bt-audio/./bt-audio.py", line 393, in main
    sanity_checks()
  File "/run/media/nicolas/Coisas/Software/bt-audio/./bt-audio.py", line 367, in sanity_checks
    if not hasattr(Gst._overrides_module, "ElementFactory"):
  File "/usr/lib64/python3.10/site-packages/gi/module.py", line 126, in __getattr__
    raise AttributeError("%r object has no attribute %r" % (
AttributeError: 'gi.repository.Gst' object has no attribute '_overrides_module'
```

There seems to be some change in the `gi` library, simply commenting out this check works fine.

**Comment by gmsoft-tuxicoman** [comment]
I changed the check. Hopefully that fixes your issue. If not, please reopen.
